package com.app.tracker.ui.scan

import android.Manifest
import android.content.pm.PackageManager
import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.Button
import android.widget.Toast
import androidx.activity.result.contract.ActivityResultContracts
import androidx.core.content.ContextCompat
import androidx.fragment.app.Fragment
import androidx.lifecycle.ViewModelProvider
import androidx.navigation.fragment.findNavController
import com.app.tracker.R
import com.app.tracker.di.ServiceLocator
import com.app.tracker.model.Task
import com.app.tracker.ui.viewmodel.TaskViewModel
import com.journeyapps.barcodescanner.ScanContract
import com.journeyapps.barcodescanner.ScanOptions
import org.json.JSONObject

class ScannerFragment : Fragment() {

    private lateinit var viewModel: TaskViewModel

    // Camera permission request launcher
    private val requestPermissionLauncher = registerForActivityResult(
        ActivityResultContracts.RequestPermission()
    ) { isGranted: Boolean ->
        if (isGranted) {
            startBarcodeScan()
        } else {
            Toast.makeText(requireContext(), R.string.toast_camera_required, Toast.LENGTH_LONG).show()
        }
    }

    // ZXing scan result launcher
    private val barcodeLauncher = registerForActivityResult(ScanContract()) { result ->
        if (result.contents == null) {
            Toast.makeText(requireContext(), R.string.toast_scan_cancelled, Toast.LENGTH_SHORT).show()
        } else {
            parseAndInsertTask(result.contents)
        }
    }

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        return inflater.inflate(R.layout.fragment_scanner, container, false)
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        val repository = ServiceLocator.provideTaskRepository(requireContext())
        val factory = TaskViewModel.TaskViewModelFactory(repository)
        viewModel = ViewModelProvider(requireActivity(), factory)[TaskViewModel::class.java]

        view.findViewById<Button>(R.id.btn_start_scan).setOnClickListener {
            checkCameraPermissionAndScan()
        }
    }

    private fun checkCameraPermissionAndScan() {
        when {
            ContextCompat.checkSelfPermission(
                requireContext(),
                Manifest.permission.CAMERA
            ) == PackageManager.PERMISSION_GRANTED -> {
                startBarcodeScan()
            }
            else -> {
                requestPermissionLauncher.launch(Manifest.permission.CAMERA)
            }
        }
    }

    private fun startBarcodeScan() {
        val options = ScanOptions().apply {
            setDesiredBarcodeFormats(ScanOptions.QR_CODE)
            setPrompt(getString(R.string.scanner_prompt))
            setCameraId(0) // Back camera
            setBeepEnabled(true)
            setBarcodeImageEnabled(false)
            setOrientationLocked(false)
        }
        barcodeLauncher.launch(options)
    }

    private fun parseAndInsertTask(data: String) {
        try {
            var title = ""
            var description = ""
            var category = "Work"
            var priority = "Medium"
            var dueDate = "2026-06-12"

            if (data.startsWith("{")) {
                // Parse JSON format
                val json = JSONObject(data)
                title = json.optString("title", getString(R.string.scanner_imported_task_default))
                description = json.optString("description", "")
                category = json.optString("category", "Work")
                priority = json.optString("priority", "Medium")
                dueDate = json.optString("dueDate", "2026-06-12")
            } else if (data.startsWith("TaskPlannerQR:")) {
                // Parse delimited text format
                val raw = data.substring(14)
                val parts = raw.split("|")
                if (parts.isNotEmpty()) title = parts[0]
                if (parts.size > 1) description = parts[1]
                if (parts.size > 2) category = parts[2]
                if (parts.size > 3) priority = parts[3]
                if (parts.size > 4) dueDate = parts[4]
            } else {
                title = data.trim()
                description = getString(R.string.scanner_scanned_from_qr)
            }

            if (title.isEmpty()) {
                title = getString(R.string.scanner_scanned_task_default)
            }

            val task = Task(
                id = 0, // Autogenerated by Room
                title = title,
                description = description,
                category = category,
                priority = priority,
                isCompleted = false,
                dueDate = dueDate
            )

            viewModel.insertTask(task)
            Toast.makeText(requireContext(), getString(R.string.toast_task_imported_success, title), Toast.LENGTH_LONG).show()

            // Navigate back to Task List
            findNavController().navigate(R.id.taskListFragment)

        } catch (e: Exception) {
            Toast.makeText(requireContext(), R.string.toast_scan_failed, Toast.LENGTH_LONG).show()
            e.printStackTrace()
        }
    }
}
